### ISSUE TITLE
Move MobileDrawer out of DashboardHeader, use at DashboardSidebar

### ISSUE THREAD

**Issue by minhdt-vietqr** [duchieupham/vietqr_web_2.0#78]
<img width="559" alt="image" src="https://github.com/user-attachments/assets/10133099-8e9e-41dc-8c1c-ae2aac25b45a">

**Comment by minhnhat-vietqr** [comment]
The item has been removed from the DashboardHeader, and changes have been pushed to the branch feat/dashboard.
